### ISSUE TITLE
Using Reading Time in Article Category Module

### ISSUE THREAD

**Issue by amelcher** [carcam/plg_readingtime#11]
I have been able to add the readingtime function to various article /category pages, but I am trying to figure out how to add it to the article category module. (standard joomla 3 version)  What would I need to add to the module in order to call the same function? Thanks,

Adam

**Comment by carcam** [comment]
Hi Adam,
I sent you this reply by email but just in case you didn't receive it:


> Thank you very much for your nice comments!! It's great that you like it.
> 
> To be honest I never thought of using, neither have tested the plugin in modules so I have no idea if it might work. As far as the module is able to trigger content plugin events, the reading time info will be there but I have not tested it. You may give it a go if you want ;)
> 
> I will not be able to check on this till mid next week, so let me know your comments if you perform any tests.

Best!!
