### ISSUE TITLE
REading time is always 1 minute

### ISSUE THREAD

**Issue by hayateen** [carcam/plg_readingtime#13]
Hello,
I love this plugin and have been using it for a very long time. 
Recently I noticed that reading time is always 1 minute no matter how long the article is. 
Any suggestions?

**Comment by carcam** [comment]
Hi hayateen, that is weird. Can you please provide a link to check and the version you are using?

**Comment by hayateen** [comment]
Hi,Thank you for your reply. 
Here is my site: www.nashiri.net 
(sorry it is in Arabic, but you can see under the title of the articles (وقت القراءة: 1 دقيقة) which indicates reading time).
I'm using version 3.51. Please see attached image. And latest version of Joomla. 
Thank you. 





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
دار ناشري للنشر الإلكتروني

حياة الياقوت

دار ناشري للنشر الإلكتروني. أول دار نشر وأول مكتبة إلكترونية مجانية غير ربحية في العالم العربي.
 |

 |

 |




    On Friday, June 1, 2018, 12:40:31 PM GMT+3, Carlos (carcam) <notifications@github.com> wrote:  
 
 
Hi hayateen, that is weird. Can you please provide a link to check and the version you are using?

**Comment by carcam** [comment]
I see the issue. Problem is with non latin writings. While I provide a release fix (sometime during this week) you may just look for the line 62 on the plugin main file (readingtime.php) and replace this:

`$countWords = str_word_count(strip_tags($fullArticle));`

With this:

`$countWords = mb_str_word_count(strip_tags($fullArticle));`

If your server supports mb functions (which it should as it's displaying text in arabics), it should work for you.

Best!!

**Comment by hayateen** [comment]
Hi,Sorry for my late reply. I only opened my email today. 
Thank :) I'll try it and let you know. 

    On Monday, June 11, 2018, 3:29:35 PM GMT+3, Carlos (carcam) <notifications@github.com> wrote:  
 
 
I see the issue. Problem is with non latin writings. While I provide a release fix (sometime during this week) you may just look for the line 62 on the plugin main file (readingtime.php) and replace this:

$countWords = str_word_count(strip_tags($fullArticle));

With this:

$countWords = mb_str_word_count(strip_tags($fullArticle));

If your server supports mb functions (which it should as it's displaying text in arabics), it should work for you.

Best!!

**Comment by hayateen** [comment]
Hi again.It did not work. When I changed the line, the front page of the site appears as a blank page. 
Thanks. 

    On Monday, June 11, 2018, 3:29:35 PM GMT+3, Carlos (carcam) <notifications@github.com> wrote:  
 
 
I see the issue. Problem is with non latin writings. While I provide a release fix (sometime during this week) you may just look for the line 62 on the plugin main file (readingtime.php) and replace this:

$countWords = str_word_count(strip_tags($fullArticle));

With this:

$countWords = mb_str_word_count(strip_tags($fullArticle));

If your server supports mb functions (which it should as it's displaying text in arabics), it should work for you.

Best!!

**Comment by carcam** [comment]
Sorry I thought your server might have full mb set.

No problem I have just published 3.5.2 release that fixes this issue ;)

https://extensions.hepta.es/downloads/estimated-reading-time

Best!!

**Comment by hayateen** [comment]
Cool. Thanks a lot :)

    On Tuesday, June 19, 2018, 7:53:12 PM GMT+3, Carlos (carcam) <notifications@github.com> wrote:  
 
 
Sorry I thought your server might have full mb set.

No problem I have just published 3.5.2 release that fixes this issue ;)

https://extensions.hepta.es/downloads/estimated-reading-time

Best!!
