### ISSUE TITLE
Problema en K2

### ISSUE THREAD

**Issue by TWAlchemist** [carcam/plg_readingtime#15]
Hola,
 estamos usando el plugin con K2 y funciona perfectamente. Solo tenemos un pequeño inconveniente. El plugin funciona en el menú base (y dentro de cada item) pero cuando se accede a un submenú todos los artículos tienen 1 minuto de tiempo estimado.

Muchas gracias por un plugin tan agradecido.

**Comment by carcam** [comment]
Hola @TWAlchemist ,
en principio el plugin no está pensado para funcionar con K2 de momento y sólo está probado para artículos de Joomla.

Si quieres podemos trabajar en adaptarlo a lo que necesitas pero Github es un sitio muy bueno para unas cosas y muy malo para dar un soporte adecuado.

Creo que si me ayudas a mejorar el plugin puedo darte soporte a través de la web del plugin. Créate una cuenta y vamos hablando por ahí:

https://extensions.hepta.es/pricing/new/free?format=html&layout=default
