### ISSUE TITLE
Traduzione italiano

### ISSUE THREAD

**Issue by tecnico10** [carcam/plg_readingtime#17]
Salve, ho installato il plugin e ho intenzione di tradurlo in italiano.
Qualche problema in particolare?
Grazie

**Comment by carcam** [comment]
No problem at all!! If you send me your translations I will add it to the plugin ;)

---

Nessun problema!! Se mi invii le tue traduzioni, lo aggiungerò al plugin;)

**Comment by tecnico10** [comment]
Ok quanto prima

Vincenzo Di Giacomo

Il ven 11 ott 2019, 15:14 Carlos (carcam) <notifications@github.com> ha
scritto:

**Comment by tecnico10** [comment]
[languages.zip](https://github.com/carcam/plg_readingtime/files/3718360/languages.zip)

due cose:
non ho trovato dove cambiare il formato testo, vorrei bold italic;
vorrei inserire uno spazio tra tempo di lettura e inizio articolo.
grazie e ciao

**Comment by carcam** [comment]
Hi tecnico10,
I have just published a new release with your translation: https://extensions.hepta.es/downloads/estimated-reading-time/estimated-reading-time-3-5-3/

Regarding your question, you can use your own styling just disabling the "Use Default Styling" setting and adding your styles in the text area below. Please check the plugin documentation for further reference:

https://extensions.hepta.es/support/documentation/estimated-reading-time/estimated-reading-time

And let me know if you need further help or have any suggestion or contribution!! Best!!

**Comment by tecnico10** [comment]
ok grazie, l'aggiornamento è riuscito direttamente da joomla.
Risolto anche il problema come mi avevi suggerito.
Buon lavoro

**Comment by tecnico10** [comment]
Ciao volevo dirti che il plugin 3.5.3 si installa come 3.5.2 e non viene riconosciuto come aggiornato.

**Comment by carcam** [comment]
I have just fixed that in 3.5.4. Grazie mile!!
