### ISSUE TITLE
Custum position

### ISSUE THREAD

**Issue by PetarG-hr** [carcam/plg_readingtime#21]
Hi, can you help me. I want to place Readingtime in custum position
I done all you write here
https://github.com/carcam/plg_readingtime/issues/16
(Edit plugin settings and set it to "hide plugin output"
Create a template override for your article view and place this code just below the picture)
After that in k2item.php I put this
<div class="estimated-reading-time"><?php echo $this->item->readingtime;?> </div>
but when load K2 item all is broken
Any help please

**Comment by carcam** [comment]
Hi @PetarG-hr

thank you for your interest in using Estimated Reading Time!!

Those instructions are meant for placing the Reading time indicator in Joomla Articles.

One of latest releases of the plugin is compatible with K2 but just for showing the reading time. I did not check how it works with K2 override system.

Best!!
