### ISSUE TITLE
Error 0 Call to undefined method Joomla\CMS\Document\HtmlDocument::getWebAssetManager()

### ISSUE THREAD

**Issue by NosyWeb** [carcam/plg_readingtime#26]
Hello,

We have this error on our Joomla 3.10.2 when we enable the plugin : 

`0 Call to undefined method Joomla\CMS\Document\HtmlDocument::getWebAssetManager()
`

We use PHP 7.4.30.

Thanks for your help.

Regards.

**Comment by carcam** [comment]
Hi NosyWeb,
You are using ERT 4.0.0 which is meant to be used in Joomla 4.

Please install ERT 3.6.5 (https://extensions.hepta.es/downloads/estimated-reading-time/estimated-reading-time-3-6-2?format=html) in your Joomla 3 sites. Once you upgrade to Joomla 4 you can use the latest release
