### ISSUE TITLE
Using in article template

### ISSUE THREAD

**Issue by joris85** [carcam/plg_readingtime#7]
Hi,

I want to use the readingtime on my own custom location in the theme.
I am not a php programmer so i do not understand the options you say under this line.
Adding reading time directly to your template overrides

Is there a full php line that i can just past in my theme where it comes?

Like this:

<div class="reading-time" style="<?php echo $customStyle; ?>">
    (<?php echo JText::_('PLG_READINGTIME_LABEL'); ?>: <?php echo $formattedTime . " " . JText::plural('PLG_READINGTIME_N_MINUTES', $slowTime ) ?>)
</div>

Thanks!

**Comment by carcam** [comment]
Hi @joris85,
thank you very much for your interest in Estimated Reading Time plugin.

Indeed there is such file you just need to use:

```
echo $this->item->readingtime->formattedtime;
```
and it will include the estimated reading time fully formatted. If you need to customize that ouput you can find how to do it in the plugin documentation in the section "Customizing plugin output with templates overrides":

http://carcam.github.io/plg_readingtime/

Best!!
